name: TruffleHog Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  trufflehog:
    name: trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@d5ef0f38cf3906dd098cea12457153c7887c1877
        with:
          extra_args: --results=verified,unknown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
